version: "2.2"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  server-agent:
    container_name: agentservice
    build:
      context: ./agentservice
      dockerfile: Dockerfile
    image: agentservice:latest
    restart: always
    ports:
      - 9090:9090
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - backend
    depends_on:
      - rabbitmq

  server-fulfilment:
    container_name: fulfilmentservice
    build:
      context: ./fulfilmentservice
      dockerfile: Dockerfile
    image: fulfilmentservice:latest
    restart: always
    ports:
      - 9091:9091
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - backend
    depends_on:
      - rabbitmq
      - server-agent

networks:
  backend:
    driver: bridge